In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv(r"D:\datasets\insurance.csv")

In [3]:
dt.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
dt["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [5]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [6]:
dt.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
charges     False
dtype: bool

In [7]:
x=dt.iloc[:,0:6].values
y=dt.iloc[:,6].values

In [8]:
x.shape

(1338, 6)

In [9]:
y.shape

(1338,)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,4,5])],remainder="passthrough")
#coverts data into binary form

x=ct.fit_transform(x)

In [11]:
x.shape

(1338, 11)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
x_train

array([[0.0, 1.0, 0.0, ..., 37, 34.1, 4],
       [0.0, 1.0, 1.0, ..., 18, 34.43, 0],
       [1.0, 0.0, 0.0, ..., 23, 36.67, 2],
       ...,
       [0.0, 1.0, 1.0, ..., 40, 25.08, 0],
       [0.0, 1.0, 1.0, ..., 19, 35.53, 0],
       [1.0, 0.0, 1.0, ..., 33, 18.5, 1]], dtype=object)

In [14]:
y_train

array([40182.246 ,  1137.4697, 38511.6283, ...,  5415.6612,  1646.4297,
        4766.022 ])

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
ann=Sequential()

In [18]:
ann.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
ann.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [20]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [21]:
ann.compile("adam","mean_squared_error",metrics=["accuracy"])

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=500)

Epoch 1/500
1070/1070 [==============================] - 3s 3ms/sample - loss: 317636762.0187 - acc: 0.0000e+00
Epoch 2/500
1070/1070 [==============================] - 1s 481us/sample - loss: 317634520.5084 - acc: 0.0000e+00s - loss: 316428849.6000 - acc: 0.00
Epoch 3/500
1070/1070 [==============================] - 0s 411us/sample - loss: 317628359.1178 - acc: 0.0000e+00
Epoch 4/500
1070/1070 [==============================] - 0s 294us/sample - loss: 317613210.5869 - acc: 0.0000e+00
Epoch 5/500
1070/1070 [==============================] - 0s 280us/sample - loss: 317581824.5981 - acc: 0.0000e+00
Epoch 6/500
1070/1070 [==============================] - 0s 336us/sample - loss: 317526817.4654 - acc: 0.0000e+00
Epoch 7/500
1070/1070 [==============================] - 0s 285us/sample - loss: 317443438.7439 - acc: 0.0000e+00
Epoch 8/500
1070/1070 [==============================] - 0s 290us/sample - loss: 317323277.3981 - acc: 0.0000e+00
Epoch 9/500
1070/1070 [==============================]

1070/1070 [==============================] - 0s 145us/sample - loss: 152038042.1682 - acc: 0.0000e+00
Epoch 72/500
1070/1070 [==============================] - 0s 121us/sample - loss: 148256730.3477 - acc: 0.0000e+00
Epoch 73/500
1070/1070 [==============================] - 0s 126us/sample - loss: 144471560.1944 - acc: 0.0000e+00
Epoch 74/500
1070/1070 [==============================] - 0s 121us/sample - loss: 140790858.5570 - acc: 0.0000e+00
Epoch 75/500
1070/1070 [==============================] - 0s 126us/sample - loss: 137226829.1290 - acc: 0.0000e+00
Epoch 76/500
1070/1070 [==============================] - 0s 126us/sample - loss: 133628820.0374 - acc: 0.0000e+00
Epoch 77/500
1070/1070 [==============================] - 0s 126us/sample - loss: 130142159.3421 - acc: 0.0000e+00
Epoch 78/500
1070/1070 [==============================] - 0s 126us/sample - loss: 126728435.2897 - acc: 0.0000e+00
Epoch 79/500
1070/1070 [==============================] - 0s 121us/sample - loss: 123388643.9

1070/1070 [==============================] - 0s 126us/sample - loss: 42847963.8804 - acc: 0.0000e+00
Epoch 143/500
1070/1070 [==============================] - 0s 126us/sample - loss: 42581374.9383 - acc: 0.0000e+00
Epoch 144/500
1070/1070 [==============================] - 0s 121us/sample - loss: 42326017.4953 - acc: 0.0000e+00
Epoch 145/500
1070/1070 [==============================] - 0s 121us/sample - loss: 42061145.8019 - acc: 0.0000e+00
Epoch 146/500
1070/1070 [==============================] - 0s 121us/sample - loss: 41808710.1159 - acc: 0.0000e+00
Epoch 147/500
1070/1070 [==============================] - 0s 121us/sample - loss: 41562938.9421 - acc: 0.0000e+00
Epoch 148/500
1070/1070 [==============================] - 0s 121us/sample - loss: 41333805.9364 - acc: 0.0000e+00
Epoch 149/500
1070/1070 [==============================] - 0s 121us/sample - loss: 41100633.4729 - acc: 0.0000e+00
Epoch 150/500
1070/1070 [==============================] - 0s 121us/sample - loss: 40870246.70

Epoch 213/500
1070/1070 [==============================] - 0s 126us/sample - loss: 34600366.7514 - acc: 0.0000e+00
Epoch 214/500
1070/1070 [==============================] - 0s 121us/sample - loss: 34572388.4561 - acc: 0.0000e+00
Epoch 215/500
1070/1070 [==============================] - 0s 117us/sample - loss: 34556872.1047 - acc: 0.0000e+00
Epoch 216/500
1070/1070 [==============================] - 0s 145us/sample - loss: 34525585.0280 - acc: 0.0000e+00
Epoch 217/500
1070/1070 [==============================] - 0s 131us/sample - loss: 34502692.4710 - acc: 0.0000e+00
Epoch 218/500
1070/1070 [==============================] - 0s 121us/sample - loss: 34484369.3570 - acc: 0.0000e+00
Epoch 219/500
1070/1070 [==============================] - 0s 131us/sample - loss: 34464318.7626 - acc: 0.0000e+00
Epoch 220/500
1070/1070 [==============================] - 0s 136us/sample - loss: 34447336.2168 - acc: 0.0000e+00
Epoch 221/500
1070/1070 [==============================] - ETA: 0s - loss: 34694

1070/1070 [==============================] - ETA: 0s - loss: 34154547.3214 - acc: 0.0000e+ - 0s 136us/sample - loss: 33910970.9570 - acc: 0.0000e+00
Epoch 283/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33908198.4822 - acc: 0.0000e+00
Epoch 284/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33905740.8299 - acc: 0.0000e+00
Epoch 285/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33901640.9645 - acc: 0.0000e+00
Epoch 286/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33898297.7327 - acc: 0.0000e+00
Epoch 287/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33904795.7607 - acc: 0.0000e+00
Epoch 288/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33906065.3234 - acc: 0.0000e+00
Epoch 289/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33892057.6065 - acc: 0.0000e+00
Epoch 290/500
1070/1070 [=====================

Epoch 353/500
1070/1070 [==============================] - 0s 136us/sample - loss: 33720635.4168 - acc: 0.0000e+00
Epoch 354/500
1070/1070 [==============================] - 0s 131us/sample - loss: 33724043.2449 - acc: 0.0000e+00
Epoch 355/500
1070/1070 [==============================] - 0s 140us/sample - loss: 33745438.7589 - acc: 0.0000e+00
Epoch 356/500
1070/1070 [==============================] - 0s 131us/sample - loss: 33715367.8056 - acc: 0.0000e+00
Epoch 357/500
1070/1070 [==============================] - 0s 131us/sample - loss: 33716056.0673 - acc: 0.0000e+00
Epoch 358/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33712185.7645 - acc: 0.0000e+00
Epoch 359/500
1070/1070 [==============================] - 0s 131us/sample - loss: 33714559.5065 - acc: 0.0000e+00
Epoch 360/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33711659.2037 - acc: 0.0000e+00
Epoch 361/500
1070/1070 [==============================] - 0s 131us/sample - los

1070/1070 [==============================] - 0s 136us/sample - loss: 33608169.5925 - acc: 0.0000e+00
Epoch 424/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33603408.8075 - acc: 0.0000e+00
Epoch 425/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33598640.2579 - acc: 0.0000e+00
Epoch 426/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33600921.2037 - acc: 0.0000e+00
Epoch 427/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33594638.7888 - acc: 0.0000e+00
Epoch 428/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33600296.8748 - acc: 0.0000e+00
Epoch 429/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33589137.9439 - acc: 0.0000e+00
Epoch 430/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33606550.7439 - acc: 0.0000e+00
Epoch 431/500
1070/1070 [==============================] - 0s 121us/sample - loss: 33596584.91

1070/1070 [==============================] - 0s 145us/sample - loss: 33507737.9290 - acc: 0.0000e+00
Epoch 494/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33510378.8860 - acc: 0.0000e+00
Epoch 495/500
1070/1070 [==============================] - 0s 110us/sample - loss: 33509473.5178 - acc: 0.0000e+00
Epoch 496/500
1070/1070 [==============================] - 0s 129us/sample - loss: 33503953.8766 - acc: 0.0000e+00
Epoch 497/500
1070/1070 [==============================] - 0s 131us/sample - loss: 33505255.1402 - acc: 0.0000e+00
Epoch 498/500
1070/1070 [==============================] - 0s 131us/sample - loss: 33504854.1645 - acc: 0.0000e+00
Epoch 499/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33503205.2262 - acc: 0.0000e+00
Epoch 500/500
1070/1070 [==============================] - 0s 126us/sample - loss: 33507492.4037 - acc: 0.0000e+00


In [23]:
ypred=ann.predict(x_test)

In [24]:
ypred

array([[ 9050.991 ],
       [ 9800.06  ],
       [44527.055 ],
       [16310.458 ],
       [ 6104.5527],
       [ 1938.6693],
       [ 4189.4106],
       [13850.04  ],
       [ 9189.581 ],
       [ 6811.9043],
       [ 5659.628 ],
       [ 9545.536 ],
       [ 9773.007 ],
       [ 5164.2397],
       [25771.82  ],
       [10692.13  ],
       [ 8989.499 ],
       [ 5447.6455],
       [ 7207.2256],
       [25306.7   ],
       [32993.42  ],
       [13252.774 ],
       [11815.524 ],
       [31170.186 ],
       [ 4325.544 ],
       [ 8853.478 ],
       [ 2830.004 ],
       [10597.194 ],
       [ 5305.803 ],
       [ 9167.882 ],
       [ 9016.741 ],
       [47271.94  ],
       [15282.717 ],
       [13025.139 ],
       [18339.107 ],
       [ 6882.922 ],
       [11483.644 ],
       [32446.049 ],
       [34938.234 ],
       [ 6477.9395],
       [ 5142.8936],
       [ 3243.9126],
       [29043.691 ],
       [45401.598 ],
       [27470.234 ],
       [ 6637.4653],
       [10577.451 ],
       [ 6483

In [25]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [27]:
yp=ann.predict(sc.transform(ct.transform([[24,"female",29.867,0,"yes","southeast"]])))

In [28]:
yp

array([[24126.14]], dtype=float32)