In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv(r"D:\datasets\Bankloan.csv")

In [3]:
dt.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dt.isnull().any()

ID                    False
Age                   False
Experience            False
Income                False
ZIP Code              False
Family                False
CCAvg                 False
Education             False
Mortgage              False
Personal Loan         False
Securities Account    False
CD Account            False
Online                False
CreditCard            False
dtype: bool

In [5]:
dt.drop(columns=["ID","ZIP Code"],inplace=True)

In [6]:
dt.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [7]:
x=dt.iloc[:,[0,1,2,3,4,5,6,8,9,10,11]].values
y=dt.iloc[:,7].values

In [8]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
y.shape

(5000,)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x_train.shape

(4000, 11)

In [12]:
y_train.shape

(4000,)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
from tensorflow.keras.models import Sequential #this library is used to initialise the model
from tensorflow.keras.layers import Dense  #used to add layers of ANN

In [15]:
ann=Sequential()

In [16]:
ann.add(Dense(11,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
ann.add(Dense(22,kernel_initializer="random_uniform",activation="relu"))

In [18]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [19]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=20)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/20
4000/4000 [==============================] - 6s 1ms/sample - loss: 0.5265 - acc: 0.9003 14s - loss: 0.6819 - acc: 0. - ETA: 11s - loss: 
Epoch 2/20
4000/4000 [==============================] - 1s 323us/sample - loss: 0.2062 - acc: 0.9025s - loss: 
Epoch 3/20
4000/4000 [==============================] - 1s 255us/sample - loss: 0.1676 - acc: 0.9025
Epoch 4/20
4000/4000 [==============================] - 1s 199us/sample - loss: 0.1415 - acc: 0.9178
Epoch 5/20
4000/4000 [==============================] - 1s 198us/sample - loss: 0.1182 - acc: 0.9592
Epoch 6/20
4000/4000 [==============================] - 1s 198us/sample - loss: 0.1008 - acc: 0.9650
Epoch 7/20
4000/4000 [==============================] - 1s 200us/sample - loss: 0.0907 - acc: 0.9678
Epoch 8/20
4000/4000 [==============================] - 1s 200us/sample - loss: 0.0829 - acc: 0.9703
Epoch 9/20
4000/4000 [===================

In [21]:
ypred=ann.predict(x_test)

In [22]:
ypred=ypred>0.5

In [23]:
ypred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [

In [24]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [25]:
yp=ann.predict(sc.transform([[30,1,65,3,1.9,1,0,0,1,1,0]]))

In [26]:
yp

array([[0.31739298]], dtype=float32)

In [27]:
yp>0.5

array([[False]])

In [30]:
yp=ann.predict_classes(sc.transform([[49,4,280,1,4.9,3,1,1,0,0,0]]))

In [31]:
yp>0.5

array([[ True]])