In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv(r"D:\datasets\Prostate_Cancer.csv")

In [3]:
dt.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [4]:
dt.isnull().any()

id                   False
diagnosis_result     False
radius               False
texture              False
perimeter            False
area                 False
smoothness           False
compactness          False
symmetry             False
fractal_dimension    False
dtype: bool

In [5]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
id                   100 non-null int64
diagnosis_result     100 non-null object
radius               100 non-null int64
texture              100 non-null int64
perimeter            100 non-null int64
area                 100 non-null int64
smoothness           100 non-null float64
compactness          100 non-null float64
symmetry             100 non-null float64
fractal_dimension    100 non-null float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


In [6]:
x=dt.iloc[:,2:10]
y=dt.iloc[:,1:2]

In [7]:
x

radius  texture  perimeter  area  smoothness  compactness  symmetry  \
0       23       12        151   954       0.143        0.278     0.242   
1        9       13        133  1326       0.143        0.079     0.181   
2       21       27        130  1203       0.125        0.160     0.207   
3       14       16         78   386       0.070        0.284     0.260   
4        9       19        135  1297       0.141        0.133     0.181   
5       25       25         83   477       0.128        0.170     0.209   
6       16       26        120  1040       0.095        0.109     0.179   
7       15       18         90   578       0.119        0.165     0.220   
8       19       24         88   520       0.127        0.193     0.235   
9       25       11         84   476       0.119        0.240     0.203   
10      24       21        103   798       0.082        0.067     0.153   
11      17       15        104   781       0.097        0.129     0.184   
12      14       15        132  1123       0.097        0.246     0.240   
13      12       22        104   783       0.084        0.100     0.185   
14      12       13         94   578       0.113        0.229     0.207   
15      22       19         97   659       0.114        0.160     0.230   
16      10       16         95   685       0.099        0.072     0.159   
17      15       14        108   799       0.117        0.202     0.216   
18      20       14        130  1260       0.098        0.103     0.158   
19      17       11         87   566       0.098        0.081     0.189   
20      16       14         86   520       0.108        0.127     0.197   
21      17       24         60   274       0.102        0.065     0.182   
22      20       27        103   704       0.107        0.214     0.252   
23      19       12        137  1404       0.094        0.102     0.177   
24       9       13        110   905       0.112        0.146     0.200   
25      19       27        116   913       0.119        0.228     0.304   
26      10       24         97   645       0.105        0.187     0.225   
27      16       24        122  1094       0.094        0.107     0.170   
28      15       15        102   732       0.108        0.170     0.193   
29      11       16        115   955       0.098        0.116     0.174   
..     ...      ...        ...   ...         ...          ...       ...   
70      21       18        124  1130       0.090        0.103     0.158   
71       9       26         59   244       0.098        0.153     0.190   
72      21       12        114   929       0.107        0.183     0.193   
73      22       25         90   584       0.101        0.128     0.166   
74      18       13         79   471       0.092        0.068     0.172   
75      21       18        104   818       0.092        0.084     0.180   
76      10       17         88   559       0.129        0.105     0.240   
77      11       21        120  1006       0.107        0.215     0.215   
78      16       18        144  1245       0.129        0.345     0.291   
79      22       16         83   506       0.099        0.095     0.172   
80      10       18         74   402       0.110        0.094     0.184   
81      17       21         86   520       0.108        0.154     0.194   
82      10       15        172  1878       0.106        0.267     0.183   
83      20       14        129  1132       0.122        0.179     0.163   
84      25       21         77   443       0.097        0.072     0.208   
85      14       13        121  1075       0.099        0.105     0.213   
86      19       26         94   648       0.094        0.099     0.208   
87      19       11        122  1076       0.090        0.121     0.195   
88      11       11         80   466       0.088        0.094     0.193   
89      12       23         96   652       0.113        0.134     0.212   
90      23       27         95   663       0.090        0.086     0.169   
91      10       12        10

In [8]:
y

diagnosis_result
0                 M
1                 B
2                 M
3                 M
4                 M
5                 B
6                 M
7                 M
8                 M
9                 M
10                M
11                M
12                B
13                M
14                M
15                M
16                M
17                M
18                M
19                B
20                B
21                B
22                M
23                M
24                M
25                M
26                M
27                M
28                M
29                M
..              ...
70                M
71                B
72                M
73                M
74                B
75                M
76                B
77                M
78                M
79                B
80                B
81                B
82                M
83                M
84                B
85                M
86                M
87                M
88                B
89                B
90                B
91                M
92                B
93                B
94                M
95                M
96                B
97                B
98                B
99                M

[100 rows x 1 columns]

In [9]:
x=x.values

In [10]:
y=y.values

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
#coverts data into binary form

y=ct.fit_transform(y)

In [12]:
print(y)

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [13]:
y.shape

(100, 2)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential #this library is used to initialise the model
from tensorflow.keras.layers import Dense  #used to add layers of ANN

In [17]:
ann=Sequential()

In [18]:
ann.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
ann.add(Dense(16,kernel_initializer="random_uniform",activation="relu"))

In [20]:
ann.add(Dense(2,kernel_initializer="random_uniform",activation="softmax"))

In [21]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=20)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/20
80/80 [==============================] - 3s 39ms/sample - loss: 0.6929 - acc: 0.5625
Epoch 2/20
80/80 [==============================] - 0s 938us/sample - loss: 0.6926 - acc: 0.5625
Epoch 3/20
80/80 [==============================] - 0s 2ms/sample - loss: 0.6921 - acc: 0.5625
Epoch 4/20
80/80 [==============================] - 0s 750us/sample - loss: 0.6917 - acc: 0.5625
Epoch 5/20
80/80 [==============================] - 0s 1ms/sample - loss: 0.6912 - acc: 0.5625
Epoch 6/20
80/80 [==============================] - 0s 938us/sample - loss: 0.6906 - acc: 0.5625
Epoch 7/20
80/80 [==============================] - 0s 875us/sample - loss: 0.6899 - acc: 0.5625
Epoch 8/20
80/80 [==============================] - 0s 563us/sample - loss: 0.6890 - acc: 0.5625
Epoch 9/20
80/80 [==============================] - 0s 750us/sample - loss: 0.6880 - acc: 0.5750
Epoch 10/20
80/80 [===================

In [23]:
ypred=ann.predict(x_test)

In [24]:
ypred

array([[0.47457293, 0.5254271 ],
       [0.5184928 , 0.48150718],
       [0.44771186, 0.5522881 ],
       [0.53553414, 0.46446586],
       [0.5168499 , 0.48315006],
       [0.50937194, 0.4906281 ],
       [0.5010346 , 0.4989654 ],
       [0.5259435 , 0.47405642],
       [0.52392614, 0.47607377],
       [0.45359126, 0.5464088 ],
       [0.45489892, 0.5451011 ],
       [0.53679717, 0.46320283],
       [0.43171608, 0.5682839 ],
       [0.49387625, 0.5061237 ],
       [0.48427805, 0.5157219 ],
       [0.4502632 , 0.54973686],
       [0.4668471 , 0.5331529 ],
       [0.46143252, 0.5385674 ],
       [0.45053118, 0.54946876],
       [0.47915316, 0.52084684]], dtype=float32)

In [25]:
y_test

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [31]:
yp=ann.predict(sc.transform([[42,15,123,844,0.147,0.175,0.345,0.101]]))

In [32]:
yp>0.5

array([[False,  True]])

In [34]:
yp=ann.predict(sc.transform([[39,31,183,687,0.179,0.143,0.211,0.081]]))

In [35]:
yp

array([[0.4421121, 0.5578879]], dtype=float32)

In [36]:
yp>0.5

array([[False,  True]])