In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r"D:\datasets\housing1.csv")

In [3]:
data.head()

no of years old  cost
0              0.00  1500
1              0.10  1550
2              0.17  1560
3              0.40  1800
4              0.70  2000

In [4]:
data.isnull().any()

 no of years old    False
cost                False
dtype: bool

In [5]:
x = data.iloc[:,0:1].values
y = data.iloc[:,1].values

In [6]:
x

array([[ 0.  ],
       [ 0.1 ],
       [ 0.17],
       [ 0.4 ],
       [ 0.7 ],
       [ 1.1 ],
       [ 1.3 ],
       [ 1.6 ],
       [ 1.8 ],
       [ 2.  ],
       [ 2.4 ],
       [ 2.7 ],
       [ 3.1 ],
       [ 3.5 ],
       [ 3.9 ],
       [ 4.25],
       [ 4.65],
       [ 4.9 ],
       [ 5.12],
       [ 5.33],
       [ 5.67],
       [ 5.9 ],
       [ 6.4 ],
       [ 6.65],
       [ 6.9 ],
       [ 7.12],
       [ 7.45],
       [ 7.89],
       [ 8.4 ],
       [ 8.8 ],
       [ 9.7 ],
       [10.5 ],
       [11.3 ],
       [11.9 ],
       [12.6 ],
       [13.11],
       [14.21],
       [14.76],
       [15.47],
       [15.89],
       [16.34],
       [17.5 ],
       [17.67],
       [19.  ],
       [19.5 ],
       [19.9 ]])

In [7]:
y

array([ 1500,  1550,  1560,  1800,  2000,  2300,  2500,  2750,  2900,
        3200,  3650,  3900,  4250,  4600,  4900,  5270,  5700,  5950,
        6120,  6333,  6698,  6920,  7345,  7560,  7999,  8120,  8350,
        8900,  9750, 10250, 11400, 13000, 14100, 14900, 15600, 16250,
       17800, 18450, 19110, 19630, 20870, 21950, 22150, 24650, 28210,
       30100], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
ypred = lr.predict(x_test)

In [11]:
ypred

array([ 9269.5971049 ,  8347.09244024, 10909.60539762,  1043.93051172,
        3222.06652549, 13600.24400286, 11422.10798909,  3606.4434691 ,
        7411.7752108 , 14625.24918581])

In [12]:
y_test

array([ 8120,  7345,  9750,  2000,  3650, 13000, 10250,  3900,  6698,
       14100], dtype=int64)

In [13]:
pv = lr.predict([[1]])
pv

array([1428.30745533])

In [14]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)
accuracy

0.9605356429296975

In [15]:
lr.score(x_test,y_test)

0.948819639167938

In [16]:
lr.score(x_train,y_train)

0.9796480128761581